import './globals.css';
import React from 'react';

export const metadata = {
    title: 'Landing template',
    description: 'Generated by Next.js',
};

export default async function RootLayout({
    children,
}) {
    return (
        <html lang="en">
        <body>
        {children}
        </body>
        </html>
    );
}
